### ISSUE TITLE
Optional parameters changed from undefined to "undefined"

### ISSUE THREAD

**Issue by gazever** [teifip/gcf-api-router#2]
pathToRegexp returns missing optional parameters as `undefined`,

gcf-api-router changes this to the string "undefined"

`return decodeURIComponent(value);` <- line 103 inside the `function decode(value) {`

turns `undefined` into `"undefined"`

**Comment by teifip** [comment]
@gazever Thanks a lot for reporting the issue. I have just published `v1.0.2` which fixes the issue. Again, thanks.
